spring:
  application:
    name: "Hubble Data Source Manager"
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: update

security:
  basic:
    enabled: false

server:
    port: 9000

galaxy:
#  url: http://galaxy.migcloud.org
  url: http://localhost:8080

xnat:
  url: http://xnat.migcloud.org/xnat
#  url: http://192.168.99.100:8080/xnat
  timeoutInMillis: 2000

guava:
  cache:
    spec: expireAfterWrite=30m

staging:
  dir: /opt/staging

---

spring:
  profiles: development

  datasource:
    url: jdbc:postgresql://localhost:5432/hubble
    username: <username>
    password: <password>
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: DEBUG

---

spring:
  profiles: production

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

galaxy:
  url: http://galaxy.migcloud.org

xnat:
  url: http://xnat.migcloud.org/xnat
  timeoutInMillis: 1000
